In [130]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [131]:
# load
df=pd.read_csv('solar_system.csv')
df

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [132]:
df = df.set_index("Attribute").T
print(f'first:{df.T.shape}')
df.index.name = "Planet"
print(f'seccond:{df.T.shape}')

df.reset_index(inplace=True)
print(f'third :{df.T.shape}')

df.columns.name = None
print(f'fourth:{df.T.shape}')

first:(20, 10)
seccond:(20, 10)
third :(21, 10)
fourth:(21, 10)

In [133]:
print(f"before: {df.shape}")

before: (10, 21)

In [134]:
print(f"after: {df.T.shape}")#21 columns and 10rows bf it was 21 rows 10 col

after: (21, 10)

In [135]:
# df = df.set_index("Attribute").T- this tranfrorms my df but first moves attribute col to index swtiches the rest

In [136]:
# df.index.name = "Planet"- this makes a new name of the transpose row index to planer

In [137]:
# df.reset_index(inplace=True)-moves 'plantet back into place of the original column, now i think its a numericla val instead of names

In [138]:
# df.columns.name = None - no relabels on the new columns

In [139]:
# Why isn’t the new shape (11, 20)? What’s different about the structure?- this is bc of the df.set_index so we made it the new index 1,2,.. so its not counted as a coulm

In [140]:
list(df.columns)

['Planet',
 'Mass (10^24kg)',
 'Diameter (km)',
 'Density (kg/m^3)',
 'Gravity (m/s^2)',
 'Escape Velocity (km/s)',
 'Rotation Period (hours)',
 'Length of Day (hours)',
 'Distance from Sun (10^6 km)',
 'Perihelion (10^6 km)',
 'Aphelion (10^6 km)',
 'Orbital Period (days)',
 'Orbital Velocity (km/s)',
 'Orbital Inclination (deg)',
 'Orbital Eccentricity',
 'Obliquity to Orbit (deg)',
 'Mean Temperature (C)',
 'Surface Pressure (bars)',
 'Number of Moons',
 'Ring System?',
 'Global Magnetic Field?']

In [141]:
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [142]:
# (f) How many columns have units? List them. How many don’t? List them.

# dont: planet, orbital eccedntruy, number of moons, ring sys, global magnetic field. 5 total
# have:mass, diam, density, gravity, escape vel, rotation period, lenght of day, dis from sun, perihelion, orbital period, orbiarl inclination, obliquiety to orbit, mean tempteratue, surface pressue, (16 total)

# i printed df aboe

In [143]:
# 2.12
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [144]:
# df[col].apply(type):
for col in df.columns:
    print(f"{col}:{df[col].apply(type).unique()}")

Planet:[<class 'str'>]
Mass (10^24kg):[<class 'str'>]
Diameter (km):[<class 'str'>]
Density (kg/m^3):[<class 'str'>]
Gravity (m/s^2):[<class 'str'>]
Escape Velocity (km/s):[<class 'str'>]
Rotation Period (hours):[<class 'str'>]
Length of Day (hours):[<class 'str'>]
Distance from Sun (10^6 km):[<class 'str'>]
Perihelion (10^6 km):[<class 'str'>]
Aphelion (10^6 km):[<class 'str'>]
Orbital Period (days):[<class 'str'>]
Orbital Velocity (km/s):[<class 'str'>]
Orbital Inclination (deg):[<class 'str'>]
Orbital Eccentricity:[<class 'str'>]
Obliquity to Orbit (deg):[<class 'str'>]
Mean Temperature (C):[<class 'str'>]
Surface Pressure (bars):[<class 'str'>]
Number of Moons:[<class 'str'>]
Ring System?:[<class 'str'>]
Global Magnetic Field?:[<class 'str'>]

In [145]:
# (a) What types are the actual values?
# - none
# (b) Why is storing numeric values as strings a problem for data analysis?
# - you cant plot them or do anything with them involving math

In [146]:
# # Planet", "Ring System?" and "Global Magnetic Field
# pd.to_numeric(df['Mass (10^24kg)'], errors="coerce")
# pd.to_numeric(df['Diameter (km)'], errors="coerce")
# pd.to_numeric(df['Density (kg/m^3)'], errors="coerce")
# pd.to_numeric(df['Gravity (m/s^2)'], errors="coerce")
# pd.to_numeric(df['Escape Velocity (km/s)'], errors="coerce")
# pd.to_numeric(df['Rotation Period (hours)'], errors="coerce")
# pd.to_numeric(df['Length of Day (hours)'], errors="coerce")
# pd.to_numeric(df['Distance from Sun (10^6 km)'], errors="coerce")
# pd.to_numeric(df['Perihelion (10^6 km)'], errors="coerce")
# pd.to_numeric(df['Aphelion (10^6 km)'], errors="coerce")
# pd.to_numeric(df['Orbital Period (days)'], errors="coerce")
# pd.to_numeric(df['Orbital Velocity (km/s)'], errors="coerce")
# pd.to_numeric(df['Orbital Inclination (deg)'], errors="coerce")
# pd.to_numeric(df['Orbital Period (days)'], errors="coerce")
# pd.to_numeric(df['Orbital Eccentricity'], errors="coerce")
# pd.to_numeric(df['Obliquity to Orbit (deg)'], errors="coerce")
# pd.to_numeric(df['Orbital Eccentricity'], errors="coerce")
# pd.to_numeric(df['Obliquity to Orbit (deg)'], errors="coerce")
# pd.to_numeric(df['Mean Temperature (C)'], errors="coerce")
# pd.to_numeric(df['Surface Pressure (bars)'], errors="coerce")
# pd.to_numeric(df['Number of Moons'], errors="coerce")
# pd.to_numeric(df['Surface Pressure (bars)'], errors="coerce")
# pd.to_numeric(df['Surface Pressure (bars)'], errors="coerce")


# much easier way i realized omg 
for col in df.columns:
    if col not in ["Planet", "Ring System?", "Global Magnetic Field?"]:
        df[col]=pd.to_numeric(df[col], errors="coerce")

In [147]:
df.dtypes

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

In [148]:
# 2hat are the three different data types now in the DataFrame?
# float64, int64, object
# (b) Define each one (e.g., float64).
# -float64=uses 64 bits to rep the wide range of numbers, int64-used to store whole num, object-base class
# (c) Which columns are still object, and why?- plante, and the last 2. this is bc i coded it to ve changing the col thats not planet or those 2 to be numerci

In [149]:
# 2.2 Apply Astropy Units

In [150]:
# akes a column name
# • Applies an Astropy unit
# • (If applicable) renames the column using df.rename()
# def attach_units(old_col, new_col,unit_scale, unit):
#     new_values = []
#     for val in df[old_col]:
#         new_values.append(float(val) * unit_scale * unit)
        
#     df[old_col] = [v.value for v in new_values]
#     unit = 1e24 * u.kg
#     new_values = []
#     for val in df[old_col]:
#         new_values.append(val)
#     df.rename(columns={old_col: new_col}, inplace=True)
#     return new_values
    
# mass_with_units = attach_units(
#     df,
#     old_col = "Mass (10^24kg)",
#     new_col  = "Mass (kg)",
#     unit_scale = 1e24,
#     unit    = u.kg
# )


def attach_units(df, old_col, new_col, unit_scale, unit):
    new_values = []
    for val in df[old_col]:
        new_values.append(float(val) * unit_scale * unit)

    df[old_col] = [v.value for v in new_values]
    df.rename(columns={old_col: new_col}, inplace=True)

    return new_values 

mass_with_units = attach_units(
    df,
    old_col    = "Mass (10^24kg)",
    new_col    = "Mass (kg)",
    unit_scale = 1e24,
    unit       = u.kg
)

print(df["Mass (kg)"])
print("\nWith units:")
for planet, val in zip(df["Planet"], mass_with_units):
    print(f"  {planet}: {val:.3e}")

0    3.300000e+23
1    4.870000e+24
2    5.970000e+24
3    7.300000e+22
4    6.420000e+23
5    1.898000e+27
6    5.680000e+26
7    8.680000e+25
8    1.020000e+26
9    1.300000e+22
Name: Mass (kg), dtype: float64

With units:
  Mercury: 3.300e+23 kg
  Venus: 4.870e+24 kg
  Earth: 5.970e+24 kg
  Moon: 7.300e+22 kg
  Mars: 6.420e+23 kg
  Jupiter: 1.898e+27 kg
  Saturn: 5.680e+26 kg
  Uranus: 8.680e+25 kg
  Neptune: 1.020e+26 kg
  Pluto: 1.300e+22 kg

In [151]:
df = pd.read_csv('solar_system.csv',index_col=0)
orbital_period = df.iloc[10].astype(float)
perihelion     = df.iloc[8].astype(float)
aphelion       = df.iloc[9].astype(float)
semi_major_axis = ((perihelion + aphelion) / 2)* 1e6 * u.km
semi_major_axis

Mercury    5.790000e+07
Venus      1.082000e+08
Earth      1.496000e+08
Moon       3.845000e+05
Mars       2.280000e+08
Jupiter    7.785000e+08
Saturn     1.432050e+09
Uranus     2.867050e+09
Neptune    4.515000e+09
Pluto      5.906350e+09
dtype: float64

In [152]:
df = pd.read_csv('solar_system.csv')
df = df.set_index("Attribute").T
df.index.name = "Planet"
df.reset_index(inplace=True)
df.columns.name = None
au_value = const.au.to(u.km).value
perihelion = df['Perihelion (10^6 km)'].astype(float).values * 1e6 / au_value * u.AU
aphelion   = df['Aphelion (10^6 km)'].astype(float).values   * 1e6 / au_value * u.AU
semi_major_axis = (perihelion + aphelion) / 2

aphelion_idx = df.columns.get_loc('Aphelion (10^6 km)')
df.insert(aphelion_idx + 1, 'semi_major_axis (AU)', semi_major_axis.value)

df.columns
print("Column names after insert:")
print(df.columns.tolist())
for planet, val in zip(df['Planet'], semi_major_axis):
    print(f"  {planet}: {val:.6f}")

Column names after insert:
['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'semi_major_axis (AU)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']
  Mercury: 0.387038 AU
  Venus: 0.723272 AU
  Earth: 1.000014 AU
  Moon: 0.002570 AU
  Mars: 1.524086 AU
  Jupiter: 5.203951 AU
  Saturn: 9.572663 AU
  Uranus: 19.165046 AU
  Neptune: 30.180911 AU
  Pluto: 39.481511 AU

In [153]:
df.head(10)

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [154]:
# Convert orbital period from days to years with astropy
orbital_period_day = df['Orbital Period (days)'].astype(float).values * u.day
orbital_period_yr  = orbital_period_day.to(u.year)
df['Orbital Period (days)'] = orbital_period_yr.value
df.rename(columns={'Orbital Period (days)': 'Orbital Period (years)'}, inplace=True)
print("Column names after rename:")
print(df.columns.tolist(), "\n")

print("Orbital Period (years) column:")
print(df['Orbital Period (years)'], "\n")

earth_period = df.loc[df['Planet'] == 'Earth', 'Orbital Period (years)'].values[0]
print(f"Earth's orbital period: {earth_period:.4f} years")

Column names after rename:
['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'semi_major_axis (AU)', 'Orbital Period (years)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

Orbital Period (years) column:
0      0.240931
1      0.615195
2      0.999863
3      0.074743
4      1.880903
5     11.857632
6     29.423682
7     83.748118
8    163.723477
9    247.939767
Name: Orbital Period (years), dtype: float64

Earth's orbital period: 0.9999 years

In [155]:
# Define AU in your own words.
# -its a unit of lenght that represents an exact number in meters

 # Print one AU with Astropy: const.au.
m=const.au
print("one AU:",m)
print(f"in km: {m.to(u.km):4f}")
#  How many kilometers are in one AU? Use Astropy to answer for you. 149597870.70000002
# • Convert all distance columns in kilometers to AU.
print(f"km in one au:{m.to(u.km).value:.2f}km\n")

one AU:   Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2
in km: 149597870.700000 km
km in one au:149597870.70km

In [156]:
# Rename the columns (e.g., "Diameter (km)" becomes "Diameter (AU)")
from astropy import units as u
from astropy import constants as const

au_value = const.au.to(u.km).value
new_columns = {
    'Diameter (km)' : 'Diameter (AU)',
    'Distance from Sun (10^6 km)':'Distance from Sun (AU)',
    'Perihelion (10^6 km)': 'Perihelion(AU)',
    'Aphelion (10^6 km)':'Aphelion (AU)',
    'semi_major_axis (km)':'semi_major_axis (AU)',    
}
scaled_cols = {
    'Distance from Sun (10^6 km)',
    'Perihelion (10^6 km)',
    'Aphelion (10^6 km)',
}

for old_name in new_columns:
    if old_name not in df.columns:
        continue
    values_km = df[old_name].astype(float)
    if old_name in scaled_cols:
        values_km = values_km * 1e6          # 10^6 km → km
    df[old_name] = (values_km.values * u.km).to(u.AU).value  
df.rename(columns=new_columns, inplace=True)
print(df.columns.tolist())
# Print a sample value from each converted column for your favorite planet.
planet = 'Earth'
row = df.loc[df['Planet'] == planet]
for new_name in new_columns.values():
    if new_name in df.columns:
        val = row[new_name].values[0]
        print(f"{planet} — {new_name}: {val:.6f} AU")

['Planet', 'Mass (10^24kg)', 'Diameter (AU)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (AU)', 'Perihelion(AU)', 'Aphelion (AU)', 'semi_major_axis (AU)', 'Orbital Period (years)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']
Earth — Diameter (AU): 0.000085 AU
Earth — Distance from Sun (AU): 1.000014 AU
Earth — Perihelion(AU): 0.983303 AU
Earth — Aphelion (AU): 1.016726 AU
Earth — semi_major_axis (AU): 1.000014 AU

In [157]:
df.to_csv("units.csv", index=False)

In [158]:
# FFFTS FILES